### ISSUE TITLE
No Submit on mobile

### ISSUE THREAD

**Issue by treading0light** [vladbatushkov/graphville-community#15]
**Describe the bug**
Using the app in a mobile chrome browser causes the submit button attached to tasks and quiz's to have no effect. 

**To Reproduce**
Episode 1 

**Screenshots**

**Expected behavior**
Submit should send my answer to be checked for correctness.

**Comment by vladbatushkov** [comment]
hi, @treading0light the reality is that we do not plan to support Mobile Web resolution in nearest future.
