### ISSUE TITLE
I want to join Graphville author club!

### ISSUE THREAD

**Issue by makarov05bm** [vladbatushkov/graphville-community#16]
Hi there! I'm Oussama, a full stack web developer and a neo4j and Cypher enthusiast, I've started using Cypher this year on my projects, and I'd really appreciate getting a chance to help you in the graphVille platform, helping with creating the new episodes or on the improvement of the website.

Looking forward to hearing from you.

**Comment by vladbatushkov** [comment]
hello, @venum0x5 if you interested to join Author club - pls, demonstrate your Author skills 👍🏻 here is few home work tasks for you to solve:
- go over Public chapters and suggest content fixes.
- open upcoming chapters and suggest scenario for story.
- share few examples of real cards + queries for upcoming episodes.
