### ISSUE TITLE
Typos in Graphville Season 1 Episode 1

### ISSUE THREAD

**Issue by tekwizz123** [vladbatushkov/graphville-community#21]
**Describe the bug**
The line `Episode can be about Graphville ordinary life or something crazy` should be plural, not singular for `Graphville 1.1 - How it Works?`. Therefore it should be `Episodes can be about Graphville ordinary life or something crazy`

Additionally for 1.3 Test Card we have the line `They are simple and most important useful.` which should be `They are simple and most importantly useful.` Also `Try any options until you know the Answer and task Solved.` should be `Try any options until you know the answer and the task is solved`.

For 1.4 Task Card, the line `Rewrite the query as much as you need, and execute query until you know the Answer and task solved.` should be `Rewrite the query as much as you need, and execute the query until you know the Answer and have solved the task.`

**Comment by vladbatushkov** [comment]
Thanks @tekwizz123 I understand fixing typos it a bit boring routine. But I appreciate the time and issue you raise to make Graphville a better education place. All your founds are fixed. Please, let me know if you found something else or have any other bigger idea for improvement! Cheers.
