### ISSUE TITLE
What that button stands for ?

### ISSUE THREAD

**Issue by GillesBodart** [vladbatushkov/graphville-community#3]
![image](https://user-images.githubusercontent.com/10420055/189129844-e3642273-f9ee-4cbf-a373-b0def060ea8f.png)

If it's because the story is not released yet I think that a small explanatory message could be more appreciated than that pure unauthorized

**Comment by vladbatushkov** [comment]
> a small explanatory message
Thank for suggestion, Gilles. You are right. I already created a ticket to provide a better explanation of what is the current progress of an episode in "Work In Progress" status, instead of permission denied button.

**Comment by vladbatushkov** [comment]
Short-term fix - provide a better message "Under Construction". **Released in version 0.1.42.**
Long-term solution: Episodes under construction will contains detailed description of the current development state. Reference to idea #2.
