### ISSUE TITLE
Welcome to Graphville (s1e1)

### ISSUE THREAD

**Issue by kramer-sb** [vladbatushkov/graphville-community#4]
### Education Score
First of all, Graphville is an educational platform, and the main goal is to teach beginners Cypher and Neo4j basics. What do you think about the lesson's usefulness, correctness, and relevance?

Materials provide a useful knowledge
- [ ] 1 (no, it is not)
- [ ] 2 (no, but somehow)
- [ ] 3 (yes, good enough)
- [x] 4 (yes, above my expectation)
- [ ] 5 (yes, the best I have ever seen)

Material is relevant to the lesson's topic
- [ ] 1 (no, materials are bad)
- [ ] 2 (no, some materials are not good)
- [ ] 3 (yes, materials are normal)
- [ ] 4 (yes, materials are good)
- [x] 5 (yes, materials are great)

Any comments?
- This first episode was a lot of fun, really enjoyed it! 

### Challenge Score
Without a challenge, there is no satisfaction with the result. Not super easy, but also not too hard and boring. So, what do you think about the lesson's tasks?

Tasks are intuitive and easy to solve
- [ ] 1 (no, tasks are too hard)
- [ ] 2 (no, tasks are too easy)
- [ ] 3 (yes, tasks are so-so)
- [ ] 4 (yes, tasks are good)
- [x] 5 (yes, tasks are perfect)

Information is enough to solve tasks
- [ ] 1 (no, need to use external resources)
- [ ] 2 (no, hard to find needed info, but possible)
- [ ] 3 (yes, somehow possible)
- [x] 4 (yes, good enough)
- [ ] 5 (yes, absolutely)

Experience with GraphUI and writing Cypher
- [ ] 1 (no, very bad)
- [ ] 2 (no, not good experience)
- [ ] 3 (yes, ok it works)
- [x] 4 (yes, good, no problems)
- [ ] 5 (yes, my experience was perfect)

Any comments?

### Engagement Score
Graphville lessons aim to educate with involvement in the story, joy, and fun. Do you like the story behind a lesson?

The data of graph was interesting to explore
- [ ] 1 (no, not at all)
- [ ] 2 (no, poor graph)
- [ ] 3 (yes, normal graph)
- [ ] 4 (yes, good graph)
- [x] 5 (yes, wonderful graph)

The storytelling behind the lesson was engaging
- [ ] 1 (no, suck story)
- [ ] 2 (no, not really)
- [ ] 3 (yes, I am neutral about the story)
- [ ] 4 (yes, I like the story)
- [x] 5 (yes, it was amazing story)

Any comments?
- I really love that our protagonist is Rambo! Most excellent. 
- This whole exercise was really nice, good primer into graphs with Neo4j can do. Looking forward to continuing!

**Comment by vladbatushkov** [comment]
Thank you @kramer-sb ❤️ Typo is fixed for future feedbacks 😆 New episodes coming this November!
