### ISSUE TITLE
REX cypher parsing error

### ISSUE THREAD

**Issue by GillesBodart** [vladbatushkov/graphville-community#7]
I like the error handling when you make a parsing error on the cypher query 

![image](https://user-images.githubusercontent.com/10420055/196287083-aa8ec21f-56f6-4e02-9a9b-7846cc4f5a52.png)

but I think adding a small phrase that says something like "Oooops, it seems that you have a typo somewhere ;-)" 

As I"m used to debug (and also cyper pro certified :p) I quickly spotted my mistake

**Comment by vladbatushkov** [comment]
Thanks for idea. Ooops message is provided. Not the best CSS styles for now, but will beautify it later.
