### ISSUE TITLE
Hint on hard questions

### ISSUE THREAD

**Issue by GillesBodart** [vladbatushkov/graphville-community#8]
Add an Hint after several attempt on the Cypher question to avoid the Dead lock and drop from students

**Comment by vladbatushkov** [comment]
Great suggestion. I already do provide hints inside the description. But now will do it a more fun / better way. As a separate feature, kind of. Moreover, will make sure that hints are provided for every query.

**Comment by vladbatushkov** [comment]
<img width="348" alt="Screen Shot 2022-10-20 at 23 57 20" src="https://user-images.githubusercontent.com/6023235/197011999-456c5f0b-e862-4e07-985a-981efe4b2778.png">

Add a "Hint" button, from version 0.1.49. For now there are several Hints for some tasks. In future, I plan to have hints for all tasks. What questions are required hints or better hints now (as you mention "hard" tasks required hints, something "hard" right now to provide hint)? @GillesBodart

**Comment by GillesBodart** [comment]
You could add in the database a counter on failed attempts and go from most
attempt to fewest to make you an idea of the understood air not ?

Le jeu. 20 oct. 2022, 18:59, Vlad Batushkov ***@***.***> a
écrit :

**Comment by vladbatushkov** [comment]
Sure, @GillesBodart I understood your idea and implemented just a minimal part for now; data-driven version of it saved into a Trello task and will wait for a further grow of the platform.
