### ISSUE TITLE
Error while opening the first public episode

### ISSUE THREAD

**Issue by finallyjeck** [vladbatushkov/graphville-community#9]
**Describe the bug**
Trying to open the first episode I encountered errors

**To Reproduce**
1. Go to 'Storybook'
2. Click on 'Welcome to graphville Season 1 episode 1'
3. Click on 'Open episode'
4. See an error

**Screenshots**
![ERROR_graphville](https://user-images.githubusercontent.com/113972758/196382876-a35bacb4-c1b5-4d7e-ac54-cd2d2815cf70.JPG)

**Expected behavior**
Start the first episode

Thank yoy, I found your site on linkedIn suggested by Tomaz Bratanic and I thought It will be interesting to see what you did.

**Comment by vladbatushkov** [comment]
Thanks, @finallyjeck issue fixed.
